#!/bin/bash
# This hook makes sure unifier passses with an exit code of 0
pylint tetravex.py
mypy tetravex.py

# Bash is awesome, and the exit code of this single line script will
# Be the same exit code as the unifier.sh script
